name: Stable Release

on:
  release:
    types:
      - created
    branches:
      - 'main'

jobs:
  stable-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Publish Stable Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm version patch --no-git-tag-version
          npm publish --tag latest

      - name: Create Stable Release Tag
        run: git tag -a "stable-${{ github.run_id }}" -m "Stable release version"
